### ISSUE TITLE
xStream Startup Error - 'Globalsearch'

### ISSUE THREAD

**Issue by SoraSuiseki** [xStream-Kodi/plugin.video.xstream#12]
Hey guys,
I'm using Jarvis v16 Kodi and installed the new xStream addon Release v3.2.0. Version of my URLResolver is v3.0.26.

But when i try to start the xStream Addon, i get this Error Message:
KeyError: 'globalsearch'
/plugin.video.xstream/resources/lib/handler/pluginHandler.py
line 121, in __updateSettings

**Comment by sraedler** [comment]
lösch mal die Einstellungsdatei und Versuch es erneut.

**Comment by SoraSuiseki** [comment]
Ich habe unter "Userdata\addon_data\" den kompletten Ordner "plugin.video.xstream" gelöscht und daraufhin xStream gestartet. Dabei wurde der Ordner wieder erstellt und alle dazugehörigen Dateien heruntergeladen. Nun funktioniert xStream einwandfrei!!!

Danke dir sraedler!
