### ISSUE TITLE
Favoriten Funktion 

### ISSUE THREAD

**Issue by ilyas-hallak** [xStream-Kodi/plugin.video.xstream#13]
Könnte es die Möglichkeit geben, vor allem Serien als Favorit zu speichern? Dies könnte man als Menüpunkt verfügbar machen und ermöglicht das schnelle springen zu bestimmten Punkten statt sie jedes Mal mühevoll raus zu suchen.

Please inform if I should write this in english.

**Comment by Viper2k4** [comment]
Heho,

du kannst doch jetzt schon die dafür vorgesehen funktion im Kodi verwenden. "Zu Favoriten hinzufügen". Dann sind dort alle Einträge die du möchtest :)

**Comment by ilyas-hallak** [comment]
Moin und Danke für die schnelle Antwort :).
Ok diese Funktion ist scheinbar komplett an mir vorbei gegangen 🙈.
