### ISSUE TITLE
kinox.ag | example call

### ISSUE THREAD

**Issue by bittorf** [xStream-Kodi/plugin.video.xstream#14]
nice project!

is it possible to "somehow" standalone-call sites/kinox_to.py and
get an download-URL for a specific link?

e.g.
```
input = "http://kinox.to/Stream/Vikings-1.html,s1e01"
output = "https://r5---sn-4g57knzd.c.drive.google.com/videoplayback?id=da664c6415ea8...."
```

**Comment by sraedler** [comment]
Aktuell nicht möglich und wird es vermutlich auch nicht.
Du kannst es jedoch einbauen und als PR posten

**Comment by bittorf** [comment]
ok, werde mal damit spielen - mal sehen wie weit ich komme.
