### ISSUE TITLE
HDfilme.tv | Autoplay

### ISSUE THREAD

**Issue by Crashdummyy** [xStream-Kodi/plugin.video.xstream#16]
Ich nutze xStream gerne zum Bingewatching.
Die Sortierung ist bei HD Filme leider nicht mehr richtig, ( 360 --> 1080 --> 720 ), als ich ( ein paar monate her ) über HDfilme gestreamt habe, war die Liste noch richtig sortiert ( 1080 als erstes )

Fix ?

**Comment by sraedler** [comment]
Addon wurde eingestellt, Sie https://xstream-kodi.github.io/
