### ISSUE TITLE
Globale Suche: Meldung "Es wurden keine Einträge gefunden" ist irreführend

### ISSUE THREAD

**Issue by tobbi** [xStream-Kodi/plugin.video.xstream#17]
Wenn eine globale Suche gestartet wird, ist die Meldung "Es wurden keine Einträge gefunden" (welche erscheint, wenn bei einer durchsuchten Seite keine Einträge gefunden werden konnten) irreführend.

Meiner Meinung nach sollte die Meldung nur erscheinen, wenn bei keinem der aktivierten Hoster irgendwelche Einträge gefunden werden konnten.

**Comment by sraedler** [comment]
Addon wurde eingestellt, Sie https://xstream-kodi.github.io/
