### ISSUE TITLE
Serienstream_to.py script error in neuer Login funktionalität

### ISSUE THREAD

**Issue by j0nxs** [xStream-Kodi/plugin.video.xstream#27]
Durch die neue Ergänzung ist es nichtmehr möglich serienstream zu nutzen, da oGui vergessen wurde zu deklarieren und bei oGui.showInfo() ein Argument fehlt in der Methode prepareWatch()

**Comment by j0nxs** [comment]
Fix:
`def prepareWatch():
    oGui = cGui()
    
    username = cConfig().getSetting('serienstream.user')
    password = cConfig().getSetting('serienstream.pass')
    if (username == '' or password == ''): oGui.showInfo('xStream', 'Logindaten wurden vergessen!')

    oRequestHandler = cRequestHandler(URL_LOGIN, caching=False)
    oRequestHandler.addHeaderEntry('X-Requested-With', 'XMLHttpRequest')
    oRequestHandler.addResponse('email', username)
    oRequestHandler.addResponse('password', password)
    oRequestHandler.request()`

**Comment by sraedler** [comment]
Hi,

bitte wende dich an die neuen Maintainer:
https://github.com/lastship/plugin.video.xstream
