### ISSUE TITLE
NameError: global name 'oGui' is not defined

### ISSUE THREAD

**Issue by PhilippMeissner** [xStream-Kodi/plugin.video.xstream#28]
https://github.com/xStream-Kodi/plugin.video.xstream/blob/4c5e0ccc49c05eda8876c5d42a33023480b70cef/sites/serienstream_to.py#L185

`oGui` ist an dieser Stelle (noch) nicht definiert.
Schätzungsweise reicht es, beim starten der Methode `oGui = cGui()` aufzurufen, um die Klasse zu instanziieren..

**Comment by sraedler** [comment]
Addon wurde eingestellt, Sie https://xstream-kodi.github.io/
