### ISSUE TITLE
AutoUpdate der URL Resolver funktioniert nicht mehr

### ISSUE THREAD

**Issue by Maetran** [xStream-Kodi/plugin.video.xstream#29]
Das automatische Updaten der Resolver gibt mir immer einen Error zurück (funktionierte bis ca. Mitte November). Habe versucht diverse Settings umzustellen, erfolglos. Werde auf verlangen auch Log nachliefern. Oder ist das Problem bereits bekannt?
Updaten von X-Stream selber läuft allerdings zuverlässig...
xstream läuft bei mir auf einer WeTek Core mit LE 8.2.2 / Kodi 17.6

**Comment by MrTschi** [comment]
Das Repo des URL-Resolvers wurde wohl gelöscht:
https://api.github.com/repos/jsergio123/script.module.urlresolver/commits/master

**Comment by styler2go** [comment]
Gibt es hier schon Lösungsansätze?

**Comment by Maetran** [comment]
leider bin ich selbst (noch) zu schlecht auf der brust um hier brauchbare lösungen unterbreiten zu können. warum das repo gelöscht wurde kann ich nicht sagen, jedoch wäre ich um eine lösung dankbar.
gruss maetran

**Comment by MrTschi** [comment]
Die Datei:
https://github.com/xStream-Kodi/plugin.video.xstream/blob/nightly/resources/lib/updateManager.py

Zeile 18+19 neue URLs eintragen
z.B. das Repo:
https://github.com/tvaddonsco/script.module.urlresolver


VG

**Comment by breaksrmine** [comment]
Für alle Fragen schlicht im offiziellen Forum vorbei schauen. Dort findet ihr auch alle Antworten auf die bisher gestellten Fragen und deren Lösungen.
http://www.lastship.square7.ch/forum/forumdisplay.php?fid=15

**Comment by renegade2k** [comment]
Das "offizielle Forum" befindet sich laut der xStream Homepage (https://xstream-kodi.github.io/) bzw. laut genau dem Projekt hier unter http://xstream-addon.square7.ch/ und die Homepage ist eben gänzlich nicht erreichbar.
Vielleicht sollte das angepasst werden, damit eben Leute mit solchen "banalen" Fragen genau dort landen und nicht auf 404 ;)

**Comment by breaksrmine** [comment]
Kodi Addons werden immer wieder fallen gelassen und zu einem späteren Zeitpunkt von Dritten weiterentwickelt und somit am Leben gehalten oder reaktiviert. Freunde dich mit dem Gedanken an, dass es deshalb immer wieder tote Seiten geben wird, weil die aktuellen Entwickler eben mittlerweile andere Personen sind. Das ist Gang und Gäbe bei Kodi. Es gibt keine xstream Homepage (mehr), nur das Forum. Kodiaddons leben nunmal von Ihren Nutzern; und in diesem Fall geht es aben an einer anderen Stelle mit anderen Entwicklern/Nutzern weiter.

**Comment by renegade2k** [comment]
Es sollte ja auch kein Vorwurf sein. Weder an Entwickler, noch an Nutzer, noch an dich ;)
Ich meinte das Ganze eigentlich mehr als ein Hinweis, weil ich selbst seit Wochen auf Ferhlersuche war, nur um dann in irgend einem Forum von einem x-beliebigen User hingewiesen zu werden "pass auf, das Addon ist tot, aber lastship ist der Nachfolger".
So sollte eventuell auch der Link mit der Homepage, Forum etc. nicht einfach nur ins 404 laufen, sondern zumindest auf eine Seite, die unerfahrenen Nutzern (wie mir auch) sagt, "xStream ist eingestellt. Es gibt Alternativen wie z.B. LastShip". Alles andere kann man sich dann ja "ergooglen"

**Comment by breaksrmine** [comment]
Kein Ding. Es steht ja nun zumindest hier in Stein gemeißelt ;).

**Comment by sraedler** [comment]
Ich habe nichts mehr damit zu tun, aber das Addon wurde eingestellt und ein Hinweis ist unter https://xstream-kodi.github.io/
