### ISSUE TITLE
URL Resolver und Xstream Update Fehler auf Xbox One

### ISSUE THREAD

**Issue by Linke360** [xStream-Kodi/plugin.video.xstream#30]
Ich benutze Kodi auf der Xbox One in der Version 18.0 bekomme es aber nicht zum laufen. Er zeigt mir den URL Resolver Update Fehler an und den Xstream Update Fehler, hinzu kommt noch ein Error Fenster das mit ImportError : No module named_winreg beginnt. Wäre echt cool wenn man das beheben könnte. 
Danke
Einen guten Rutsch ins neue Jahr

**Comment by sraedler** [comment]
Addon wurde eingestellt, Sie https://xstream-kodi.github.io/

**Comment by Assimaschine** [comment]
Ist auf der xbox schlicht und ergreifend gesperrt. Genauso wie zugriff auf usb Datenträger. Also die light Version. Nervt,ich weiss.
