### ISSUE TITLE
Lastship Homepage Adresse -> Error

### ISSUE THREAD

**Issue by MartinX3** [xStream-Kodi/plugin.video.xstream#31]
Leider klappt der Link nicht, da du "https" eingetragen hast.
Der Webanbieter lenkt wohl die Adresse nicht intelligent um, wenn kein Zertifikat hinterlegt wurde.

PS:
Warum hast du dieses Plugin eigentlich eingestellt?
Bietet das andere Plugin den selben Umfang und du hilfst nun da mit?

**Comment by sraedler** [comment]
Danke, habs geändert.

Eingestellt wurde es nur hier, ein full fork ist auf der neuen Seite und recht gut gepflegt.
LastShip ist deutlich besser als xstream, versuch es.
Ich selber lese nur die Commits auf Github, da ich momentan keine Zeit habe. Würde jedoch gerne wieder mitwirken.

**Comment by MartinX3** [comment]
Danke dir! :)

Wieso gibt es dann noch einen Fork, anstatt nur ein Projekt, an dem alle Mitwirken?

**Comment by sraedler** [comment]
Das ist eine lange Geschichte ;)

Kurzversion: xstream lag brach. Es wurde an Exodus auf deutsch gearbeitet. Exodus starb. Lastship als fork entstand. Xstream wird rudimentär gemaintained.

Aber wie gesagt ich hab da nichts in meiner Entscheidungsgewalt.

Schau einfach mal ins Forum, da gehts bisschen mehr ab als hier

**Comment by MartinX3** [comment]
Hihi, danke dir.
Ich hab mir direkt LastShip geschnappt und es funktioniert, wie es soll. :)

Dann ist Xstream wie OpenOffice und LastShip wie LibreOffice :P
